services:
  pg:
    build: ../docker
    restart: always
    container_name: pg
    environment:
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
      POSTGRES_DB: dhis
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "15432:5432"
    volumes:
      - ../docker/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ../docker/dhis.tgz:/docker-entrypoint-initdb.d/dhis.tgz
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
